# Generated by Django 3.0.1 on 2020-02-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
