# Generated by Django 3.0.1 on 2020-02-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_eval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval',
            name='overall',
            field=models.CharField(choices=[('5점', '5점'), ('4점', '4점'), ('3잠', '3점'), ('2점', '2점'), ('1점', '1점')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eval',
            name='ratio',
            field=models.CharField(choices=[('학점느님', '학점느님'), ('골고루', '골고루'), ('깐깐징어', '깐깐징어'), ('F 박격포', 'F 박격포')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eval',
            name='semester',
            field=models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], max_length=5, null=True),
        ),
    ]
