# Generated by Django 3.0.1 on 2020-02-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200221_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval',
            name='overall',
            field=models.CharField(choices=[('5점', '5점'), ('4점', '4점'), ('3점', '3점'), ('2점', '2점'), ('1점', '1점')], max_length=5, null=True),
        ),
    ]
