# Generated by Django 3.0.1 on 2020-02-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200221_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval',
            name='overall',
            field=models.CharField(choices=[('5점', '5점'), ('4점', '4점'), ('3점', '3점'), ('2점', '2점'), ('1점', '1점')], default=50, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eval',
            name='ratio',
            field=models.CharField(choices=[('', '학점느님'), ('골고루', '골고루'), ('깐깐징어', '깐깐징어'), ('F 박격포', 'F 박격포')], default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eval',
            name='semester',
            field=models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], default=50, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eval',
            name='text',
            field=models.TextField(default=50),
            preserve_default=False,
        ),
    ]
