# Generated by Django 3.0.1 on 2020-02-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20200221_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eval',
            old_name='ratio',
            new_name='ratio_select',
        ),
    ]
