# Generated by Django 3.0.1 on 2020-02-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20200221_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eval',
            old_name='text',
            new_name='texts',
        ),
    ]
