# Generated by Django 3.0.1 on 2020-02-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20200221_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eval',
            name='ratio_select',
            field=models.CharField(choices=[('학점느님', '학점느님'), ('골고루', '골고루'), ('깐깐징어', '깐깐징어'), ('F 박격포', 'F 박격포')], max_length=10),
        ),
    ]
