# Generated by Django 3.0.1 on 2020-02-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_evals_lect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evals',
            name='lect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalposts', to='crud.Lecture'),
        ),
    ]
