# Generated by Django 3.0.1 on 2020-02-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_auto_20200222_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evals',
            name='lect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Lecture'),
        ),
    ]
